name: Hollow Bone Healing Lodge
favicon: null
layout_spectrum: 0.90792
typography_spectrum: 1
title: Hollow Bone Healing Lodge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7e534b'
    - '#d2bd92'
    - '#362325'
    - '#9da5d7'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
